---
title: "ILI Prediction - All States"
author: "Rob Carnell"
date: "March 28, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

################################################################################
# Packages

require(magrittr)
require(dplyr)
require(ggplot2)
require(mgcv)
require(readr)
require(MMWRweek)
require(assertthat)
require(forecast)
require(triangle)

################################################################################
# filenames

today_date <- "2020-05-22" # before Sunday, Friday is best

ili_input_file <- file.path("data", paste0("ILI_data_", today_date, ".RData"))
covid_input_file <- file.path("data", paste0("COVID19_data_", today_date, 
                                             ".RData"))
ili_state_auto_arima_output_file <- file.path("data", 
                                              "ILI_state_auto_arima.RData")
ili_state_auto_arima_results_output_file <- file.path("data", 
                                                      "ILI_state_auto_arima_results.RData")
covid_results_output_file <- file.path("data", "covid_results.Rdata")
ili_state_arima_plus_output_file <- file.path("data", 
                                              paste0("ILI_state_arima_plus_", 
                                                     today_date, ".Rdata"))

load(ili_input_file)
load(covid_input_file)

sapply(list.files("src", full.names = TRUE), function(z) {source(z); return(TRUE)}, USE.NAMES = FALSE)

################################################################################
# Constants

current_ili_week <- 20 # max(model_data_post$week)
current_ili_year <- 2020
current_ili_date <- as.Date("2020-05-10") # Sunday - MMWRweek(current_ili_date)

assertthat::assert_that(current_ili_week == MMWRweek(today_date)$MMWRweek - 1)
assertthat::assert_that(current_ili_week == MMWRweek(current_ili_date)$MMWRweek)

ili_covid_state_forecast_file <- file.path("state-forecast-data", 
                                           "bertcarnell-arima_glm",
                                           paste0("2020-ew", current_ili_week, 
                                                  "-bertcarnell-arima_glm.csv"))
```

## Combine Datasets

```{r combine, echo=FALSE}
temp_covid <- covid_daily %>% 
  subset(Country_Region == "US" & 
           Province_State %in% hhs_regions_map$state) %>%
  group_by(Province_State, mmwryear, mmwrweek) %>%
  summarise(confirmed = max(Confirmed, na.rm = TRUE),
            active = max(Active, na.rm = TRUE))

temp_covid_nyc <- covid_daily %>%
  subset(Country_Region == "US" & 
           Combined_Key == "New York City, New York, US") %>%
  group_by(Province_State, mmwryear, mmwrweek) %>%
  summarise(confirmed = max(Confirmed, na.rm = TRUE),
            active = max(Active, na.rm = TRUE))

stateflu3 <- merge(stateflu, temp_covid, by.x = c("region", "year", "week"),
                   by.y = c("Province_State", "mmwryear", "mmwrweek"),
                   all.x = TRUE, all.y = FALSE)
temp_nyc <- merge(subset(stateflu, region == "New York City" & year == 2020), 
      temp_covid_nyc, by.x = c("year", "week"),
      by.y = c("mmwryear", "mmwrweek"),
      all.x = FALSE, all.y = FALSE)

stateflu3 <- within(stateflu3, 
                    confirmed[which(region == "New York City" & 
                                    year == 2020 & 
                                    week %in% temp_covid_nyc$mmwrweek)] <- temp_nyc$confirmed)
stateflu3 <- within(stateflu3, 
                    active[which(region == "New York City" & 
                                   year == 2020 & 
                                   week %in% temp_covid_nyc$mmwrweek)] <- temp_nyc$active)
```

## ARIMA for each state

#### Build an auto.arima model for each state

```{r arima, echo=FALSE}
if (!file.exists(ili_state_auto_arima_output_file))
{
  arima_model_list <- vector("list", length(hhs_regions_map$state))
  for (i in seq_along(hhs_regions_map$state))
  {
    print(paste0(i, ": ", as.character(hhs_regions_map$state[i])))
    if (as.character(hhs_regions_map$state[i]) %in% 
        c("Commonwealth of the Northern Mariana Islands")) 
      next
    model_state <- hhs_regions_map$state[i]
    model_data <- subset(stateflu3, stateflu3$region == model_state)
    arima_model_list[[i]] <- state_auto_arima_build(model_state, model_data)
  }
  # QA the fits
  for (i in seq_along(hhs_regions_map$state))
  {
    if (as.character(hhs_regions_map$state[i]) %in% 
        c("Commonwealth of the Northern Mariana Islands")) 
      next
    if (any(is.na(sqrt(diag(vcov(arima_model_list[[i]]$arima_model))))))
    {
      stop("NA in coefficient standard errors")
    }
  }
       
  save(arima_model_list, file = ili_state_auto_arima_output_file)  
} else
{
  load(ili_state_auto_arima_output_file)
}

arima_result_list <- vector("list", length(hhs_regions_map$state))
for (i in seq_along(hhs_regions_map$state))
{
  print(paste0(i, ": ", as.character(hhs_regions_map$state[i])))
  if (as.character(hhs_regions_map$state[i]) %in% 
      c("Commonwealth of the Northern Mariana Islands")) 
    next
  model_state <- hhs_regions_map$state[i]
  model_data <- subset(stateflu3, stateflu3$region == model_state)
  arima_result_list[[i]] <- state_arima_build(model_state, model_data,
                                              arima_model_list[[i]])
}
save(arima_result_list, file = ili_state_auto_arima_results_output_file)
```

#### COVID Daily Prediction for Each State

```{r predict, echo=FALSE}
covid_result_list <- vector("list", length(hhs_regions_map$state))
for (i in seq_along(hhs_regions_map$state))
{
  print(paste0(i, ": ", as.character(hhs_regions_map$state[i])))
  if (as.character(hhs_regions_map$state[i]) %in% 
      c("Commonwealth of the Northern Mariana Islands")) 
    next
  model_state <- hhs_regions_map$state[i]
  arl <- arima_result_list[[i]]
  covid_result_list[[i]] <- covid_prediction_builder(
    model_state, arl$mean_inflation, 
    arl$model_data_post$total_patients[nrow(arl$model_data_post)])
}
save(covid_result_list, file = covid_results_output_file)
```

#### Add COVID prediction to ILI prediction

```{r res, echo=FALSE}
arima_plus_result_list <- vector("list", length(hhs_regions_map$state))
for (i in seq_along(hhs_regions_map$state))
{
  print(paste0(i, ": ", as.character(hhs_regions_map$state[i])))
  if (as.character(hhs_regions_map$state[i]) %in% 
      c("Commonwealth of the Northern Mariana Islands")) 
    next
  crl <- covid_result_list[[i]]
  arl <- arima_result_list[[i]]
  assertthat::assert_that(length(arl$arima_fcst$mean) == length(crl$covid_daily_state_post$pred_ili) +
                            length(crl$covid_daily_state_pred$pred_ili),
                          msg = paste("Error in prediction lengths in", hhs_regions_map$state[i]))
  arima_plus_result_list[[i]] <- create_result_from_arima_fcst_plus(
    arl$arima_fcst,
    c(crl$covid_daily_state_post$pred_ili, 
      crl$covid_daily_state_pred$pred_ili),
    c(crl$covid_daily_state_post$pred_ili_se,
      crl$covid_daily_state_pred$pred_ili_se),
    c(crl$covid_daily_state_post$mmwrweek, 
      crl$covid_daily_state_pred$mmwrweek),
    arima_result_list[[i]]$model_data_post$unweighted_ili)
}
save(arima_plus_result_list, file = ili_state_arima_plus_output_file)

```

#### Write Out

```{r writeout, echo=FALSE}
## make ILI targets template
ili_bin_template <- expand.grid(
  location = flusight_states, target = ili_targets, type = "bin", bin = ili_bins, 
  value = as.character(NA), stringsAsFactors = FALSE)
ili_points_template <- expand.grid(
  location = flusight_states, target = ili_targets, type = "point", 
  value = as.character(NA), stringsAsFactors = FALSE)

## make date targets template
date_bins_template <- expand.grid(
  location = flusight_states, target = date_targets[1], type = "bin", 
  bin = date_bins, value = as.character(NA), stringsAsFactors = FALSE)
date_points_template <- expand.grid(
  location = flusight_states, target = date_targets[1], type = "point", 
  value = as.character(NA), stringsAsFactors = FALSE)

for (i in seq_along(hhs_regions_map$state))
{
  model_state <- hhs_regions_map$state[i]
  model_state_c <- as.character(model_state)
  print(paste0(i, ": ", model_state_c))
  
  if (model_state_c == "Commonwealth of the Northern Mariana Islands")
    next
  aprl <- arima_plus_result_list[[i]]
  arl <- arima_result_list[[i]]
  len <- length(aprl$point)
  point_actual_fcst <- aprl$point
  point_actual_fcst[1:nrow(arl$model_data_post)] <- arl$model_data_post$unweighted_ili
  week_after_ew10 <- which(aprl$mmwrweeks >= 10)
  week1_week6 <- (len - WEEKS_AHEAD + 1):len
  max_week_ind <- which.max(point_actual_fcst[week_after_ew10])
  
  # point estimates for weeks 1 - 6 and peak
  ind <- which(ili_points_template$location == model_state_c)
  ili_points_template$value[ind] <- c(aprl$point[week1_week6],
                                      point_actual_fcst[week_after_ew10][max_week_ind])

  # uncertainty for week 1 - 6
  ind <- which(ili_bin_template$location == model_state_c)
  bin_results <- cbind(aprl$p_bin[, week1_week6],
                                   aprl$p_bin[, week_after_ew10[max_week_ind]])
  ili_bin_template$value[ind] <- c(t(bin_results))

  ind <- which(date_points_template$location == model_state_c)
  max_week_label <- paste0("2020-ew", aprl$mmwrweeks[week_after_ew10[max_week_ind]])
  date_points_template$value[ind] <- max_week_label

  # uncertainty in the peak epidemic week
  ind <- which(date_bins_template$location == model_state_c)
  ind_max <- which(date_bins_template$location == model_state_c &
                 date_bins_template$bin == max_week_label)
  if (length(ind) >= 2)
  {
    week_bin_p <- ptriangle(1:length(ind), a = 1, b = length(ind), c = which(ind == ind_max)) -
      ptriangle(0:(length(ind) - 1), a = 1, b = length(ind), c = which(ind == ind_max))
  } else if (length(ind) == 1)
  {
    print("only one week")
    week_bin_p <- 1
  } else
  {
    # we expect this for some of the carribean states
  }
  
  # if in the actual weeks (not the last 6), there is a maximum, then none of
  #   the other weeks are possible peaks
  actuals <- point_actual_fcst[week_after_ew10][-week1_week6]
  for (i in 1:length(actuals))
  {
    if (actuals[i] < point_actual_fcst[week_after_ew10][max_week_ind])
    {
      week_bin_p[i] <- 0
    }
  }

  date_bins_template$value[ind] <- week_bin_p / sum(week_bin_p)
}

## bind all together
state_template <- bind_rows(
    ili_bin_template, 
    ili_points_template, 
    date_bins_template, 
    date_points_template
    # binary_bins_template
) %>%
    mutate(location = factor(location, levels = flusight_states),
        type = factor(type, levels = c("point", "bin"))) %>%
    arrange(location, target, type)

write_csv(state_template, path = ili_covid_state_forecast_file)
```

#### QA

```{r qa, echo = FALSE}
## sanity checking
temp <- state_template %>%
  filter(type == "point") %>%
  group_by(target) %>%
  summarize(test = n())
assertthat::assert_that(all(temp$test == 53))

temp <- state_template %>%
  filter(type == "bin") %>%
  group_by(target) %>%
  summarize(test = n())
assertthat::assert_that(all(temp$test %in% c(53*251, 53*26)))

temp <- state_template %>%
  filter(type == "bin") %>%
  group_by(location, target) %>%
  summarize(test = sum(as.numeric(value)))
assertthat::assert_that(all(abs(temp$test - 1) < 1E-6))

if (FALSE)
{
  library(devtools)
  devtools::install_github("reichlab/cdcForecastUtils")
}
source(file.path("..", "COVID-19-ILI-forecasting-submissions-bc", "code",
                 "test-covid-forecast-formatting.R"))
```
